// Sample data
const users = [
  { id: 1, name: "John Doe", email: "john@example.com" },
  { id: 2, name: "Jane Doe", email: "jane@example.com" },
  { id: 3, name: "Alice Smith", email: "alice@example.com" },
  { id: 4, name: "Bob Johnson", email: "bob@example.com" },
  { id: 5, name: "Charlie Brown", email: "charlie@example.com" },
  { id: 6, name: "Diana Prince", email: "diana@example.com" },
  { id: 7, name: "Evan Wright", email: "evan@example.com" },
  { id: 8, name: "Fiona Green", email: "fiona@example.com" },
  { id: 9, name: "George Harris", email: "george@example.com" },
  { id: 10, name: "Hannah Clark", email: "hannah@example.com" },
];

const posts = [
  { id: 1, userId: 1, title: "Post 1", body: "This is post 1 by John Doe" },
  { id: 2, userId: 1, title: "Post 2", body: "This is post 2 by John Doe" },
  { id: 3, userId: 1, title: "Post 3", body: "This is post 3 by John Doe" },
  { id: 4, userId: 1, title: "Post 4", body: "This is post 4 by John Doe" },
  { id: 5, userId: 2, title: "Post 5", body: "This is post 1 by Jane Doe" },
  { id: 6, userId: 2, title: "Post 6", body: "This is post 2 by Jane Doe" },
  { id: 7, userId: 2, title: "Post 7", body: "This is post 3 by Jane Doe" },
  { id: 8, userId: 2, title: "Post 8", body: "This is post 4 by Jane Doe" },
  { id: 9, userId: 3, title: "Post 9", body: "This is post 1 by Alice Smith" },
  {
    id: 10,
    userId: 3,
    title: "Post 10",
    body: "This is post 2 by Alice Smith",
  },
  {
    id: 11,
    userId: 3,
    title: "Post 11",
    body: "This is post 3 by Alice Smith",
  },
  {
    id: 12,
    userId: 3,
    title: "Post 12",
    body: "This is post 4 by Alice Smith",
  },
  {
    id: 13,
    userId: 4,
    title: "Post 13",
    body: "This is post 1 by Bob Johnson",
  },
  {
    id: 14,
    userId: 4,
    title: "Post 14",
    body: "This is post 2 by Bob Johnson",
  },
  {
    id: 15,
    userId: 4,
    title: "Post 15",
    body: "This is post 3 by Bob Johnson",
  },
  {
    id: 16,
    userId: 4,
    title: "Post 16",
    body: "This is post 4 by Bob Johnson",
  },
  {
    id: 17,
    userId: 5,
    title: "Post 17",
    body: "This is post 1 by Charlie Brown",
  },
  {
    id: 18,
    userId: 5,
    title: "Post 18",
    body: "This is post 2 by Charlie Brown",
  },
  {
    id: 19,
    userId: 5,
    title: "Post 19",
    body: "This is post 3 by Charlie Brown",
  },
  {
    id: 20,
    userId: 5,
    title: "Post 20",
    body: "This is post 4 by Charlie Brown",
  },
  {
    id: 21,
    userId: 6,
    title: "Post 21",
    body: "This is post 1 by Emily Davis",
  },
  {
    id: 22,
    userId: 6,
    title: "Post 22",
    body: "This is post 2 by Emily Davis",
  },
  {
    id: 23,
    userId: 6,
    title: "Post 23",
    body: "This is post 3 by Emily Davis",
  },
  {
    id: 24,
    userId: 6,
    title: "Post 24",
    body: "This is post 4 by Emily Davis",
  },
  {
    id: 25,
    userId: 7,
    title: "Post 25",
    body: "This is post 1 by Frank Miller",
  },
  {
    id: 26,
    userId: 7,
    title: "Post 26",
    body: "This is post 2 by Frank Miller",
  },
  {
    id: 27,
    userId: 7,
    title: "Post 27",
    body: "This is post 3 by Frank Miller",
  },
  {
    id: 28,
    userId: 7,
    title: "Post 28",
    body: "This is post 4 by Frank Miller",
  },
  {
    id: 29,
    userId: 8,
    title: "Post 29",
    body: "This is post 1 by George White",
  },
  {
    id: 30,
    userId: 8,
    title: "Post 30",
    body: "This is post 2 by George White",
  },
  {
    id: 31,
    userId: 8,
    title: "Post 31",
    body: "This is post 3 by George White",
  },
  {
    id: 32,
    userId: 8,
    title: "Post 32",
    body: "This is post 4 by George White",
  },
  {
    id: 33,
    userId: 9,
    title: "Post 33",
    body: "This is post 1 by Hannah Black",
  },
  {
    id: 34,
    userId: 9,
    title: "Post 34",
    body: "This is post 2 by Hannah Black",
  },
  {
    id: 35,
    userId: 9,
    title: "Post 35",
    body: "This is post 3 by Hannah Black",
  },
  {
    id: 36,
    userId: 9,
    title: "Post 36",
    body: "This is post 4 by Hannah Black",
  },
  { id: 37, userId: 10, title: "Post 37", body: "This is post 1 by Ian Green" },
  { id: 38, userId: 10, title: "Post 38", body: "This is post 2 by Ian Green" },
  { id: 39, userId: 10, title: "Post 39", body: "This is post 3 by Ian Green" },
  { id: 40, userId: 10, title: "Post 40", body: "This is post 4 by Ian Green" },
];

module.exports = { users, posts };
